FROM cypress/browsers:node-18.12.0-chrome-114

# Define o diretório de trabalho

WORKDIR /app

# Copia os arquivos do projeto para dentro da imagem

COPY . .

# Instala as dependências do projeto

RUN npm install

# Comando padrão para rodar os testes em modo headless

CMD ["npx", "cypress", "run", "--browser", "chrome"]