version: "3.9"

services:
  banco:
    image: ernestobarbosa/lojaebacdb:latest
    environment:
      - MYSQL_DATABASE=wp_qe
      - MYSQL_USER=wp_qe
      - MYSQL_PASSWORD=ebaconline
      - MYSQL_ROOT_PASSWORD=ebaconline
    ports:
      - "3306:3306"

  loja:
    image: ernestobarbosa/lojaebac:latest
    environment:
      - WORDPRESS_DB_HOST=banco:3306   
      - WORDPRESS_DB_NAME=wp_qe
      - WORDPRESS_DB_USER=wp_qe
      - WORDPRESS_DB_PASSWORD=ebaconline
      - WORDPRESS_TABLE_PREFIX=wp_
    ports:
      - "8080:80"  
    depends_on:
      - banco

    